/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JDialogAssitencia.java
 *
 * Created on 19/01/2012, 23:11:37
 */
package br.com.ortus.gui;

import br.com.ortus.beans.Assistencia;
import br.com.ortus.beans.Atendimento;
import br.com.ortus.beans.Cliente;
import br.com.ortus.beans.Equipamento;
import br.com.ortus.beans.MoldeComponente;
import br.com.ortus.beans.Usuario;
import br.com.ortus.configuracaoPersistencia.TransactionManager;
import br.com.ortus.daosSistema.AssistenciaDao;
import br.com.ortus.daosSistema.AtendimentoDao;
import br.com.ortus.utilidades.HashSistema;
import br.com.ortus.utilidades.Utilidades;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class JDialogAssitencia extends javax.swing.JDialog {

    private Cliente clienteAtual;
    private List<Equipamento> equipamentosAstec;
    private List<MoldeComponente> moldeComponente;
    private Atendimento atendimento;

    /**
     * Creates new form JDialogAssitencia
     */
    public JDialogAssitencia(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        equipamentosAstec = new ArrayList<Equipamento>();
        moldeComponente = new ArrayList<MoldeComponente>();
        atendimento = new Atendimento();
        popularTabelaEquipamentos();
        popularTabelaComponentes();
        iniciarCalculoOrcamento();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupFreteEntrada = new javax.swing.ButtonGroup();
        buttonGroupFreteSaida = new javax.swing.ButtonGroup();
        buttonGroupResolvidoTelefone = new javax.swing.ButtonGroup();
        buttonGroupFinalizadaAstec = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButtonFechar = new javax.swing.JButton();
        jButtonNovo = new javax.swing.JButton();
        jButtonRemover = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldIDAssistencia = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldDataInicio = new javax.swing.JTextField();
        jButtonDataInicio = new javax.swing.JButton();
        jTextFieldDataFim = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButtonPesquisar = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldIDCliente4 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldNomeCliente4 = new javax.swing.JTextField();
        jTextFieldFoneCliente4 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jButtonBuscarCliente4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButtonSim = new javax.swing.JRadioButton();
        jRadioButtonNao = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAcaoImediata = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextAreaReclamacao = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldNumeroRA = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTableEquipamentos = new javax.swing.JTable();
        jButtonADDEquipamento = new javax.swing.JButton();
        jButtonRemoveEquipamento = new javax.swing.JButton();
        jButtonMostraEquipamento = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableTabelaComponentes = new javax.swing.JTable();
        jButtonADDComponente = new javax.swing.JButton();
        jButtonRemoveComponente = new javax.swing.JButton();
        jButtonMostraComponente = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldValorOrcamento = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jTextFieldDesc7 = new javax.swing.JTextField();
        jTextFieldDesc12 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldExtras = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jFormattedTextFieldDataChegada = new javax.swing.JFormattedTextField();
        jRadioButtonEntradaCliente = new javax.swing.JRadioButton();
        jTextFieldNumCorreioEntrada = new javax.swing.JTextField();
        jTextFieldValorFreteEntrada = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jRadioButtonEntradaOrtus = new javax.swing.JRadioButton();
        jButtonDataFim = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jFormattedTextFieldDataSaida = new javax.swing.JFormattedTextField();
        jRadioButtonClienteSaida = new javax.swing.JRadioButton();
        jTextFieldNumCorreioSaida = new javax.swing.JTextField();
        jTextFieldValorSaida = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jRadioButtonOrtusSaida = new javax.swing.JRadioButton();
        jButtonDataFim1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jRadioButtonFinalizadaSim = new javax.swing.JRadioButton();
        jRadioButtonFinalizadaNao = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Assistência Técnica Ortus - Cadastro de Assistência");

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Assistência Técnica");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(jLabel1)
                .addContainerGap(268, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 701, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jButtonFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortus/icones/close.png"))); // NOI18N
        jButtonFechar.setText("Fechar");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });

        jButtonNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortus/icones/folder_new.png"))); // NOI18N
        jButtonNovo.setText("Limpar");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortus/icones/trashcan_delete_17.png"))); // NOI18N
        jButtonRemover.setText("Remover");
        jButtonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverActionPerformed(evt);
            }
        });

        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortus/icones/save2.png"))); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jLabel8.setText("ID Assitência:");

        jTextFieldIDAssistencia.setEditable(false);

        jLabel9.setText("Inicio da Atendimento:");

        jTextFieldDataInicio.setEditable(false);

        jButtonDataInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortus/icones/calendar_accept.png"))); // NOI18N
        jButtonDataInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDataInicioActionPerformed(evt);
            }
        });

        jTextFieldDataFim.setEditable(false);

        jLabel10.setText("Fim do atendimento:");

        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortus/icones/pesquisarpequeno.png"))); // NOI18N
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));

        jLabel17.setText("ID:");

        jTextFieldIDCliente4.setBackground(new java.awt.Color(204, 255, 255));
        jTextFieldIDCliente4.setEditable(false);

        jLabel18.setText("Cliente:");

        jTextFieldNomeCliente4.setBackground(new java.awt.Color(204, 255, 255));
        jTextFieldNomeCliente4.setEditable(false);

        jTextFieldFoneCliente4.setBackground(new java.awt.Color(204, 255, 255));
        jTextFieldFoneCliente4.setEditable(false);

        jLabel19.setText("Telefone:");

        jButtonBuscarCliente4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortus/icones/usuariopequeno.png"))); // NOI18N
        jButtonBuscarCliente4.setText("Buscar");
        jButtonBuscarCliente4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarCliente4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jTextFieldIDCliente4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jTextFieldNomeCliente4, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jTextFieldFoneCliente4, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBuscarCliente4))
                    .addComponent(jLabel19))
                .addGap(46, 46, 46))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldIDCliente4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNomeCliente4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldFoneCliente4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBuscarCliente4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Descrição da reclamação:");

        jLabel3.setText("Resolvido por telefone:");

        buttonGroupResolvidoTelefone.add(jRadioButtonSim);
        jRadioButtonSim.setText("Sim");

        buttonGroupResolvidoTelefone.add(jRadioButtonNao);
        jRadioButtonNao.setText("Não");

        jLabel4.setText("Ação imediata");

        jTextAcaoImediata.setColumns(20);
        jTextAcaoImediata.setRows(5);
        jScrollPane4.setViewportView(jTextAcaoImediata);

        jTextAreaReclamacao.setColumns(20);
        jTextAreaReclamacao.setRows(5);
        jScrollPane5.setViewportView(jTextAreaReclamacao);

        jLabel12.setText("Nº RA:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButtonSim)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonNao))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(13, 13, 13)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addComponent(jTextFieldNumeroRA, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(jTextFieldIDAssistencia))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jTextFieldDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(jButtonDataInicio)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(jButtonPesquisar))
                        .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(37, 37, 37)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPesquisar)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDataInicio)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(4, 4, 4)
                            .addComponent(jTextFieldIDAssistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addGap(4, 4, 4)
                            .addComponent(jTextFieldNumeroRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonSim)
                            .addComponent(jRadioButtonNao)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Atendimento", jPanel1);

        jPanel14.setMaximumSize(new java.awt.Dimension(700, 450));
        jPanel14.setPreferredSize(new java.awt.Dimension(679, 450));

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Equipamento(s)"));

        jTableTableEquipamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableTableEquipamentos);

        jButtonADDEquipamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortus/icones/mais.png"))); // NOI18N
        jButtonADDEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonADDEquipamentoActionPerformed(evt);
            }
        });

        jButtonRemoveEquipamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortus/icones/trashcan_delete_17.png"))); // NOI18N
        jButtonRemoveEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveEquipamentoActionPerformed(evt);
            }
        });

        jButtonMostraEquipamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortus/icones/mostraAparelho.png"))); // NOI18N
        jButtonMostraEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostraEquipamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonADDEquipamento)
                    .addComponent(jButtonRemoveEquipamento)
                    .addComponent(jButtonMostraEquipamento))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jButtonADDEquipamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonRemoveEquipamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonMostraEquipamento))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder("Componente(s)"));

        jTableTabelaComponentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableTabelaComponentes);

        jButtonADDComponente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortus/icones/mais.png"))); // NOI18N
        jButtonADDComponente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonADDComponenteActionPerformed(evt);
            }
        });

        jButtonRemoveComponente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortus/icones/trashcan_delete_17.png"))); // NOI18N
        jButtonRemoveComponente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveComponenteActionPerformed(evt);
            }
        });

        jButtonMostraComponente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortus/icones/mostraAparelho.png"))); // NOI18N
        jButtonMostraComponente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostraComponenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonADDComponente)
                    .addComponent(jButtonRemoveComponente)
                    .addComponent(jButtonMostraComponente))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jButtonADDComponente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonRemoveComponente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonMostraComponente))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        jLabel5.setText("Total do orçamento R$:");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortus/icones/processor.png"))); // NOI18N
        jButton2.setText("Calcular Orçamento");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Com Desc. 7%");

        jLabel7.setText("Com Desc. 12%");

        jLabel11.setText("Valores Extras:");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldValorOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDesc7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addComponent(jTextFieldDesc12, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)))
                        .addGap(65, 65, 65))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldExtras, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(583, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31))))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldExtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5))
                .addGap(2, 2, 2)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDesc7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDesc12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jTextFieldValorOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(208, 208, 208))
        );

        jTabbedPane1.addTab("Manutenção/Serviço", jPanel14);

        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações de Entrada"));
        jPanel16.setToolTipText("Entrada");

        jLabel20.setText("Ident. do frete (n°correio):");

        try {
            jFormattedTextFieldDataChegada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        buttonGroupFreteEntrada.add(jRadioButtonEntradaCliente);
        jRadioButtonEntradaCliente.setText("Cliente");

        jLabel22.setText("Valor R$:");

        jLabel21.setText("Frete pago por:");

        jLabel23.setText("Data chegada:");

        buttonGroupFreteEntrada.add(jRadioButtonEntradaOrtus);
        jRadioButtonEntradaOrtus.setText("Ortus");

        jButtonDataFim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortus/icones/calendar_accept.png"))); // NOI18N
        jButtonDataFim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDataFimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(53, 53, 53)
                        .addComponent(jLabel21)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel22)
                        .addGap(86, 86, 86)
                        .addComponent(jLabel23))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(jTextFieldNumCorreioEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jRadioButtonEntradaCliente)
                        .addGap(1, 1, 1)
                        .addComponent(jRadioButtonEntradaOrtus)
                        .addGap(7, 7, 7)
                        .addComponent(jTextFieldValorFreteEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jFormattedTextFieldDataChegada, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDataFim)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23))))
                .addGap(2, 2, 2)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNumCorreioEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonEntradaCliente)
                            .addComponent(jRadioButtonEntradaOrtus)
                            .addComponent(jTextFieldValorFreteEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDataFim)
                            .addComponent(jFormattedTextFieldDataChegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações de Saída"));
        jPanel17.setToolTipText("Entrada");
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setText("Ident. do frete (n°correio):");
        jPanel17.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 16, -1, -1));

        try {
            jFormattedTextFieldDataSaida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel17.add(jFormattedTextFieldDataSaida, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 71, -1));

        buttonGroupFreteSaida.add(jRadioButtonClienteSaida);
        jRadioButtonClienteSaida.setText("Cliente");
        jPanel17.add(jRadioButtonClienteSaida, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));
        jPanel17.add(jTextFieldNumCorreioSaida, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 36, 173, -1));
        jPanel17.add(jTextFieldValorSaida, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 104, -1));

        jLabel25.setText("Valor R$:");
        jPanel17.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        jLabel26.setText("Frete pago por:");
        jPanel17.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jLabel27.setText("Data saída:");
        jPanel17.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, -1));

        buttonGroupFreteSaida.add(jRadioButtonOrtusSaida);
        jRadioButtonOrtusSaida.setText("Ortus");
        jPanel17.add(jRadioButtonOrtusSaida, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        jButtonDataFim1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortus/icones/calendar_accept.png"))); // NOI18N
        jButtonDataFim1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDataFim1ActionPerformed(evt);
            }
        });
        jPanel17.add(jButtonDataFim1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, -1, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Situação"));

        jLabel13.setText("Assistência finalizada:");

        buttonGroupFinalizadaAstec.add(jRadioButtonFinalizadaSim);
        jRadioButtonFinalizadaSim.setText("Sim");

        buttonGroupFinalizadaAstec.add(jRadioButtonFinalizadaNao);
        jRadioButtonFinalizadaNao.setText("Não");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jRadioButtonFinalizadaSim)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonFinalizadaNao)))
                .addGap(0, 507, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonFinalizadaSim)
                    .addComponent(jRadioButtonFinalizadaNao))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Recebimento/Envio", jPanel15);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jButtonSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRemover)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonNovo)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonFechar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonRemover)
                    .addComponent(jButtonNovo)
                    .addComponent(jButtonFechar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        // TODO add your handling code here:
        novo();
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:
        salvar();
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonBuscarCliente4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarCliente4ActionPerformed
        // TODO add your handling code here:
        buscarCliente();
    }//GEN-LAST:event_jButtonBuscarCliente4ActionPerformed

    private void jButtonADDEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonADDEquipamentoActionPerformed
        // TODO add your handling code here:
        adicionarEquipamento();
        popularTabelaEquipamentos();
    }//GEN-LAST:event_jButtonADDEquipamentoActionPerformed

    private void jButtonRemoveEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveEquipamentoActionPerformed
        // TODO add your handling code here:
        removerEquipamento();
    }//GEN-LAST:event_jButtonRemoveEquipamentoActionPerformed

    private void jButtonADDComponenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonADDComponenteActionPerformed
        // TODO add your handling code here:
        adicionarComponente();
        popularTabelaComponentes();
    }//GEN-LAST:event_jButtonADDComponenteActionPerformed

    private void jButtonRemoveComponenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveComponenteActionPerformed
        // TODO add your handling code here:
        removerComponente();
    }//GEN-LAST:event_jButtonRemoveComponenteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        calcularEMostrarNosJTextsOsValoresOrcamento();
    }//GEN-LAST:event_jButton2ActionPerformed

        private void jButtonDataInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDataInicioActionPerformed
            // TODO add your handling code here:
            jTextFieldDataInicio.setText(pegarData());
    }//GEN-LAST:event_jButtonDataInicioActionPerformed

    private void jButtonDataFimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDataFimActionPerformed
        // TODO add your handling code here:
        jFormattedTextFieldDataChegada.setText(pegarData());
    }//GEN-LAST:event_jButtonDataFimActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        // TODO add your handling code here:
        pesquisar();
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonDataFim1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDataFim1ActionPerformed
        // TODO add your handling code here:
        jFormattedTextFieldDataSaida.setText(pegarData());
        jTextFieldDataFim.setText(pegarData());
    }//GEN-LAST:event_jButtonDataFim1ActionPerformed

    private void jButtonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverActionPerformed
        // TODO add your handling code here:
        remover();
    }//GEN-LAST:event_jButtonRemoverActionPerformed

    private void jButtonMostraComponenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostraComponenteActionPerformed
        // TODO add your handling code here:
        exibirComponente();
    }//GEN-LAST:event_jButtonMostraComponenteActionPerformed

    private void jButtonMostraEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostraEquipamentoActionPerformed
        // TODO add your handling code here:
        exibirEquipamento();
    }//GEN-LAST:event_jButtonMostraEquipamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogAssitencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogAssitencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogAssitencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogAssitencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                JDialogAssitencia dialog = new JDialogAssitencia(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupFinalizadaAstec;
    private javax.swing.ButtonGroup buttonGroupFreteEntrada;
    private javax.swing.ButtonGroup buttonGroupFreteSaida;
    private javax.swing.ButtonGroup buttonGroupResolvidoTelefone;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonADDComponente;
    private javax.swing.JButton jButtonADDEquipamento;
    private javax.swing.JButton jButtonBuscarCliente4;
    private javax.swing.JButton jButtonDataFim;
    private javax.swing.JButton jButtonDataFim1;
    private javax.swing.JButton jButtonDataInicio;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonMostraComponente;
    private javax.swing.JButton jButtonMostraEquipamento;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonRemoveComponente;
    private javax.swing.JButton jButtonRemoveEquipamento;
    private javax.swing.JButton jButtonRemover;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataChegada;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataSaida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButtonClienteSaida;
    private javax.swing.JRadioButton jRadioButtonEntradaCliente;
    private javax.swing.JRadioButton jRadioButtonEntradaOrtus;
    private javax.swing.JRadioButton jRadioButtonFinalizadaNao;
    private javax.swing.JRadioButton jRadioButtonFinalizadaSim;
    private javax.swing.JRadioButton jRadioButtonNao;
    private javax.swing.JRadioButton jRadioButtonOrtusSaida;
    private javax.swing.JRadioButton jRadioButtonSim;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableTabelaComponentes;
    private javax.swing.JTable jTableTableEquipamentos;
    private javax.swing.JTextArea jTextAcaoImediata;
    private javax.swing.JTextArea jTextAreaReclamacao;
    private javax.swing.JTextField jTextFieldDataFim;
    private javax.swing.JTextField jTextFieldDataInicio;
    private javax.swing.JTextField jTextFieldDesc12;
    private javax.swing.JTextField jTextFieldDesc7;
    private javax.swing.JTextField jTextFieldExtras;
    private javax.swing.JTextField jTextFieldFoneCliente4;
    private javax.swing.JTextField jTextFieldIDAssistencia;
    private javax.swing.JTextField jTextFieldIDCliente4;
    private javax.swing.JTextField jTextFieldNomeCliente4;
    private javax.swing.JTextField jTextFieldNumCorreioEntrada;
    private javax.swing.JTextField jTextFieldNumCorreioSaida;
    private javax.swing.JTextField jTextFieldNumeroRA;
    private javax.swing.JTextField jTextFieldValorFreteEntrada;
    private javax.swing.JTextField jTextFieldValorOrcamento;
    private javax.swing.JTextField jTextFieldValorSaida;
    // End of variables declaration//GEN-END:variables

    private void novo() {
        jTextFieldIDAssistencia.setText(null);
        jTextFieldDataInicio.setText(null);
        jTextFieldDataFim.setText(null);
        jTextFieldIDCliente4.setText(null);
        jTextFieldNomeCliente4.setText(null);
        jTextFieldFoneCliente4.setText(null);
        jTextFieldNumCorreioEntrada.setText(null);
        jTextFieldValorFreteEntrada.setText(null);
        jFormattedTextFieldDataChegada.setText(null);
        jRadioButtonEntradaCliente.setSelected(true);
        jRadioButtonClienteSaida.setSelected(true);
        jTextFieldNumCorreioSaida.setText(null);
        jTextFieldValorSaida.setText(null);
        jFormattedTextFieldDataSaida.setText(null);
        moldeComponente = new ArrayList<MoldeComponente>();
        equipamentosAstec = new ArrayList<Equipamento>();
        jTextFieldValorOrcamento.setText(null);
        jTextFieldDesc7.setText(null);
        jTextFieldDesc12.setText(null);
        jTextAcaoImediata.setText(null);
        jTextAreaReclamacao.setText(null);
        popularTabelaComponentes();
        popularTabelaEquipamentos();
        atendimento = new Atendimento();
        jTextFieldNumeroRA.setText(null);
        jRadioButtonFinalizadaNao.setSelected(true);
    }

    private void salvar() {
        if (verificarCamposVazios() || converterNumeroRADaGui() == -1) {
            return;
        } else {
            int opcao = JOptionPane.showConfirmDialog(rootPane,
                    "Deseja salvar?", "Confirmação",
                    JOptionPane.YES_NO_OPTION);
            if (opcao != JOptionPane.YES_OPTION) {
                return;
            }
            Assistencia astec = new Assistencia();
            if (!jTextFieldIDAssistencia.getText().isEmpty()) {
                astec.setId(Integer.parseInt(jTextFieldIDAssistencia.getText()));
            }
            astec.setDataInicio(jTextFieldDataInicio.getText());
            astec.setDataFim(jTextFieldDataFim.getText().toUpperCase());
            astec.setCliente(clienteAtual);

            astec.setIdCorreioEntrada(jTextFieldNumCorreioEntrada.getText().toUpperCase());
            Double valor = pegarValorDoubleEntrada();
            if (valor == null) {
                return;
            }
            astec.setValorFreteEntrada(valor);
            astec.setFretePagoEntrada(buscarFretePagoEntrada());
            astec.setDataChegadaFrete(jFormattedTextFieldDataChegada.getText());
            astec.setIdCorreioSaida(jTextFieldNumCorreioSaida.getText().toUpperCase());
            Double valorSaida = pegarValorDoubleSaida();
            if (valorSaida == null) {
                return;
            }
            astec.setValorFreteSaida(valorSaida);
            astec.setFretePagoSaida(buscarFretePagoSaida());
            astec.setDataSaidaFrete(jFormattedTextFieldDataSaida.getText());
            astec.setValor(calcularOrcamento());
            astec.setDataModificacao(Calendar.getInstance());

            Usuario user = (Usuario) HashSistema.hash.get("usuarioLogado");
            astec.setUsuario(user);

            astec.setAtendimento(buscarAtendimento());
            astec.setEquipamentos(equipamentosAstec);
            astec.setMoldeComponentes(moldeComponente);


            TransactionManager.beginTransaction();
            AtendimentoDao atDao = new AtendimentoDao();
            AssistenciaDao aDao = new AssistenciaDao();
            try {

                atDao.persistir(atendimento);
                aDao.persistir(astec);
                TransactionManager.commit();
                JOptionPane.showMessageDialog(null, "Assitencia salva com sucesso!");
                novo();
            } catch (Exception e) {
                TransactionManager.rollback();
                JOptionPane.showMessageDialog(null, "Assitencia não pode ser salva!" + e);
            }
        }
    }

    private String pegarData() {
        String data = "";
        data = new Utilidades().calendarToString(Calendar.getInstance());
        return data;
    }

    private void buscarCliente() {
        JDialog jd = new NovoCadastroCliente(null, true);
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);
        clienteAtual = (Cliente) HashSistema.hash.get("cliente");
        if (clienteAtual == null) {
            return;
        }
        HashSistema.hash.remove("cliente");
        preencherFormularioComOCliente(clienteAtual);
    }

    private void preencherFormularioComOCliente(Cliente clienteAtual) {
        jTextFieldIDCliente4.setText(String.valueOf(clienteAtual.getId()));
        jTextFieldNomeCliente4.setText(clienteAtual.getNome());
        jTextFieldFoneCliente4.setText(clienteAtual.getTelefone1());
    }

    private void adicionarEquipamento() {
        JDialog jd = new JDialogNovoCadastroEquipamento(null, true);
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);
        Equipamento equip = (Equipamento) HashSistema.hash.get("equipamento2");
        if (equip == null) {
            return;
        } else {
            equipamentosAstec.add(equip);
            HashSistema.hash.remove("equipamento2");
        }
    }

    private void popularTabelaEquipamentos() {
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{
                    "ID", "Equipamento", "Nº Série", "Modelo"});
        //TransactionManager.commit();

        if (equipamentosAstec != null) {
            for (Equipamento equip : equipamentosAstec) {
                model.addRow(new Object[]{equip.getId(), equip.getNome(), equip.getNumeroSerie(), equip.getModelo()});
            }
            jTableTableEquipamentos.setModel(model);
        }
    }

    private void removerEquipamento() {
        int linha = jTableTableEquipamentos.getSelectedRow();
        if (linha != -1) {
            equipamentosAstec.remove(linha);
            popularTabelaEquipamentos();
        }
    }

    private void popularTabelaComponentes() {
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{
                    "ID", "Componente", "U.M.", "Valor R$", "Número Série"});


        if (moldeComponente != null) {
            for (MoldeComponente moldeComp : moldeComponente) {
                model.addRow(new Object[]{moldeComp.getComponente().getId(), moldeComp.getComponente().getNome(), moldeComp.getComponente().getUnidadeMedida(), moldeComp.getValorFinalComponente(), moldeComp.getNumeroIdentificacao()});
            }
            jTableTabelaComponentes.setModel(model);
        }
    }

    private Object calcularDescontoICMS(double perc, Double valor) {
        Double resultado = new Utilidades().calcularDescontoICMS(perc, valor);
        return new Utilidades().formatarValorDoubleParaString(resultado);
    }

    private void adicionarComponente() {
        JDialog jd = new JDialogCadastroMoldeComponente(null, true);
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);
        MoldeComponente molde = (MoldeComponente) HashSistema.hash.get("moldeComponente");
        if (molde == null) {
            return;
        } else {
            HashSistema.hash.remove("moldeComponente");
            moldeComponente.add(molde);
        }
    }

    private void removerComponente() {
        int linha = jTableTabelaComponentes.getSelectedRow();
        if (linha != -1) {
            moldeComponente.remove(linha);
            popularTabelaComponentes();
        }
    }

    private Double pegarValorDoubleEntrada() {
        if (jTextFieldValorFreteEntrada.getText().isEmpty()) {
            return 0.0;
        }
        if (new Utilidades().verificarSeEntradaENumeroDouble(jTextFieldValorFreteEntrada.getText())) {
            return new Utilidades().formatarValorStringParaDouble(jTextFieldValorFreteEntrada.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Informe um valor numérico para valor de entrada de frete.");
            return null;
        }
    }

    private String buscarFretePagoEntrada() {
        if (jRadioButtonEntradaCliente.isSelected()) {
            return "Cliente";
        } else {
            return "Ortus";
        }
    }

    private Double pegarValorDoubleSaida() {
        if (jTextFieldValorSaida.getText().isEmpty()) {
            return 0.0;
        }
        if (new Utilidades().verificarSeEntradaENumeroDouble(jTextFieldValorSaida.getText())) {
            return new Utilidades().formatarValorStringParaDouble(jTextFieldValorSaida.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Informe um valor numérico para valor.");
            return null;
        }
    }

    private String buscarFretePagoSaida() {
        if (jRadioButtonClienteSaida.isSelected()) {
            return "Cliente";
        } else {
            return "Ortus";
        }
    }

    private boolean verificarCamposVazios() {
        if (jTextFieldDataInicio.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe a data de inicio da assistência.");
            return true;
        } else if (jTextFieldValorOrcamento.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe o valor do orçamento.");
            return true;
        } else {
            return false;
        }
    }

    private Double calcularOrcamento() {
        Double valorTotal = 0.0;
        if (!equipamentosAstec.isEmpty()) {
            for (int i = 0; i < equipamentosAstec.size(); i++) {
                if (!equipamentosAstec.get(i).getMoldeComponentes().isEmpty()) {
                    for (int j = 0; j < equipamentosAstec.get(i).getMoldeComponentes().size(); j++) {
                        valorTotal += equipamentosAstec.get(i).getMoldeComponentes().get(j).getValorFinalComponente();
                    }
                }
            }
        }
        if (!moldeComponente.isEmpty()) {
            for (int i = 0; i < moldeComponente.size(); i++) {
                valorTotal += moldeComponente.get(i).getValorFinalComponente();
            }
        }
        if (jRadioButtonOrtusSaida.isSelected()) {
            if (!jTextFieldValorSaida.getText().isEmpty()) {
                if (verificarSeValorFreteSaidaEValido()) {
                    Double valorDoFrete = new Utilidades().formatarValorStringParaDouble(jTextFieldValorSaida.getText());
                    valorTotal += valorDoFrete;
                }
            }
        }
        if (!jTextFieldExtras.getText().isEmpty()) {
            if (verificarSeValorExtraEhValido()) {
                valorTotal += new Utilidades().formatarValorStringParaDouble(jTextFieldExtras.getText());
            }
        }
        return valorTotal;
    }

    private boolean verificarSeValorFreteSaidaEValido() {
        try {
            Double.parseDouble(jTextFieldValorSaida.getText());
            return true;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Numero invalido pra o valor em R$!");
            return false;
        }
    }

    private void pesquisar() {
        JDialog jd = new JDialogPesquisaAssitencia(null, true);
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);
        Assistencia astecAux = (Assistencia) HashSistema.hash.get("astec");
        if (astecAux == null) {
            return;
        } else {
            HashSistema.hash.remove("astec");
            preencherFormularioComAAstec(astecAux);
        }
    }

    private void preencherFormularioComAAstec(Assistencia astecAux) {
        jTextFieldIDAssistencia.setText(String.valueOf(astecAux.getId()));
        jTextFieldDataInicio.setText(astecAux.getDataInicio());
        jTextFieldDataFim.setText(astecAux.getDataFim());
        jTextFieldIDCliente4.setText(String.valueOf(astecAux.getCliente().getId()));
        jTextFieldNomeCliente4.setText(astecAux.getCliente().getNome());
        jTextFieldFoneCliente4.setText(astecAux.getCliente().getTelefone1());
        clienteAtual = astecAux.getCliente();
        equipamentosAstec = buscarEquipamentos(astecAux);
        moldeComponente = buscarComponentes(astecAux);
        popularTabelaEquipamentos();
        popularTabelaComponentes();
        calcularEMostrarNosJTextsOsValoresOrcamento();
        jTextFieldNumCorreioEntrada.setText(astecAux.getIdCorreioEntrada());
        if (astecAux.getFretePagoEntrada().equals("Cliente")) {
            jRadioButtonEntradaCliente.setSelected(true);
        } else {
            jRadioButtonEntradaOrtus.setSelected(true);
        }
        if (astecAux.getFretePagoSaida().equals("Cliente")) {
            jRadioButtonClienteSaida.setSelected(true);
        } else {
            jRadioButtonOrtusSaida.setSelected(true);
        }
        jTextFieldValorFreteEntrada.setText(String.valueOf(astecAux.getValorFreteEntrada()));
        jFormattedTextFieldDataChegada.setText(astecAux.getDataChegadaFrete());
        jTextFieldNumCorreioSaida.setText(astecAux.getIdCorreioSaida());
        jTextFieldValorSaida.setText(String.valueOf(astecAux.getValorFreteSaida()));
        jFormattedTextFieldDataSaida.setText(astecAux.getDataSaidaFrete());
        jTextAreaReclamacao.setText(astecAux.getAtendimento().getReclamacao());
        if (astecAux.getAtendimento().getResolvidoPorTelefone().booleanValue() == true) {
            jRadioButtonSim.setSelected(true);
        } else {
            jRadioButtonNao.setSelected(true);
        }
        jTextAcaoImediata.setText(astecAux.getAtendimento().getAcaoImediata());
        atendimento = astecAux.getAtendimento();
        int ra = 0;
        if (atendimento.getNumeroRA() != null) {
            ra = atendimento.getNumeroRA();
        }
        jTextFieldNumeroRA.setText(String.valueOf(ra));

        if (atendimento.getFinalizado() != null) {
            if (atendimento.getFinalizado().booleanValue()) {
                jRadioButtonFinalizadaSim.setSelected(true);
            } else {
                jRadioButtonFinalizadaNao.setSelected(true);
            }
        } else {
            jRadioButtonFinalizadaNao.setSelected(true);
        }
    }

    private List<Equipamento> buscarEquipamentos(Assistencia astecAux) {
        List<Equipamento> listaAux = new ArrayList<Equipamento>();
        for (int i = 0; i < astecAux.getEquipamentos().size(); i++) {
            listaAux.add(astecAux.getEquipamentos().get(i));
        }
        return listaAux;
    }

    private List<MoldeComponente> buscarComponentes(Assistencia astecAux) {
        List<MoldeComponente> listaAux2 = new ArrayList<MoldeComponente>();
        for (int i = 0; i < astecAux.getMoldeComponentes().size(); i++) {
            listaAux2.add(astecAux.getMoldeComponentes().get(i));
        }
        return listaAux2;
    }

    private Atendimento buscarAtendimento() {
        if (atendimento.getId() != null) {
            atendimento.setId(atendimento.getId());
        }
        int numeroRa = converterNumeroRADaGui();
        atendimento.setNumeroRA(numeroRa);
        atendimento.setReclamacao(jTextAreaReclamacao.getText().toUpperCase());
        atendimento.setResolvidoPorTelefone(verificarSolucao());
        atendimento.setAcaoImediata(jTextAcaoImediata.getText().toUpperCase());
        if (jRadioButtonFinalizadaSim.isSelected()) {
            atendimento.setFinalizado(true);
        } else {
            atendimento.setFinalizado(false);
        }
        return atendimento;
    }

    private int converterNumeroRADaGui() {
        int ra = 0;
        try {
            ra = Integer.parseInt(jTextFieldNumeroRA.getText());
            return ra;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Informe um numero para RA!");
            ra = -1;
            return ra;
        }
    }

    private Boolean verificarSolucao() {
        if (jRadioButtonSim.isSelected()) {
            return true;
        } else {
            return false;
        }
    }

    private void calcularEMostrarNosJTextsOsValoresOrcamento() {
        Double valor = calcularOrcamento();
        jTextFieldValorOrcamento.setText(String.valueOf(valor));
        jTextFieldDesc7.setText(new Utilidades().formatarValorDoubleParaString(new Utilidades().calcularDescontoICMS(7.0, valor)));
        jTextFieldDesc12.setText(new Utilidades().formatarValorDoubleParaString(new Utilidades().calcularDescontoICMS(12.0, valor)));
    }

    private void remover() {
        if (jTextFieldIDAssistencia.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Busque uma assistência técnica para remover.");
            return;
        } else {
            int opcao = JOptionPane.showConfirmDialog(rootPane,
                    "Deseja remover?", "Confirmação",
                    JOptionPane.YES_NO_OPTION);
            if (opcao != JOptionPane.YES_OPTION) {
                return;
            }
            int id = Integer.parseInt(jTextFieldIDAssistencia.getText());
            TransactionManager.beginTransaction();
            try {
                AssistenciaDao asDao = new AssistenciaDao();
                Assistencia astecExcluir = asDao.obterPorId(id);
                asDao.remover(astecExcluir);

                TransactionManager.commit();
                JOptionPane.showMessageDialog(null, "Removido com sucesso!");
                novo();
            } catch (Exception e) {
                TransactionManager.rollback();
                JOptionPane.showMessageDialog(null, "Erro na remoção. Motivo: " + e);
            }
        }
    }

    private void iniciarCalculoOrcamento() {
        new Thread() {

            @Override
            public void run() {
                while (true) {
                    calcularEMostrarNosJTextsOsValoresOrcamento();
                    try {
                        sleep(900);
                    } catch (Exception e) {
                        System.out.println(e);
                    }
                }
            }
        }.start();
    }

    private boolean verificarSeValorExtraEhValido() {
        try {
            Double.parseDouble(jTextFieldExtras.getText());
            return true;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Numero invalido pra o valor em R$!");
            return false;
        }
    }

    private void exibirComponente() {
        int linha = jTableTabelaComponentes.getSelectedRow();
        if (linha != -1) {
            moldeComponente.get(linha);
            popularTabelaComponentes();
        }
    }

    private void exibirEquipamento() {
        int linha = jTableTableEquipamentos.getSelectedRow();
        if (linha != -1) {
            Equipamento equipamento = equipamentosAstec.get(linha);
            HashSistema.hash.put("equipamento", equipamento);
            JDialog jd = new JDialogNovoCadastroEquipamento(null, true);
            jd.setLocationRelativeTo(null);
            jd.setVisible(true);
            popularTabelaEquipamentos();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha para visualizar o equipamento.");
            return;
        }
    }
}
