/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ortus.gui;

import br.com.ortus.beans.Log;
import br.com.ortus.beans.TabelaTroca;
import br.com.ortus.beans.Usuario;
import br.com.ortus.configuracaoPersistencia.TransactionManager;
import br.com.ortus.daosSistema.LogDao;
import br.com.ortus.daosSistema.TabelaTrocaDao;
import br.com.ortus.utilidades.HashSistema;
import br.com.ortus.utilidades.Utilidades;
import java.net.InetAddress;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrador
 */
public class JDialogTabelaTroca extends javax.swing.JDialog {

    /**
     * Creates new form JDialogTabelaTroca
     */
    private List<TabelaTroca> trocasPendentes;
    private List<TabelaTroca> trocasEnviadas;
    private List<TabelaTroca> trocasEstoque;

    public JDialogTabelaTroca(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        trocasPendentes = new ArrayList<TabelaTroca>();
        trocasEnviadas = new ArrayList<TabelaTroca>();
        trocasEstoque = new ArrayList<TabelaTroca>();
        povoarTabelaPendente();
        povoarTabelaEnviado();
        povoarTabelaEstoque();



    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldQtd = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextFieldDataPedido = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jFormattedTextFieldDataMaxEnvio = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldObs = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jFormattedTextFieldDataProducao = new javax.swing.JFormattedTextField();
        jComboBoxStatusProducao = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jComboBoxDevolucao = new javax.swing.JComboBox();
        jComboBoxEquipamento = new javax.swing.JComboBox();
        jTextFieldID = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabelQtdeCarac = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePendentes = new javax.swing.JTable();
        jButtonAlterar = new javax.swing.JButton();
        jTextFieldResultado = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableEnviados = new javax.swing.JTable();
        jTextFieldResultadoEnviadas = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButtonAlterar1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableEnviadosEstoqueAstec = new javax.swing.JTable();
        jTextFieldResultadoEstoqueAsstec = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButtonAlterar2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tabela de Troca de Equipamentos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(428, 428, 428))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro"));

        jLabel2.setText("Cliente");

        jLabel3.setText("Qtd");

        jLabel4.setText("Equipamento");

        try {
            jFormattedTextFieldDataPedido.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldDataPedido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldDataPedidoFocusLost(evt);
            }
        });

        jLabel5.setText("Data do Pedido");

        jLabel6.setText("Data max. Envio");

        try {
            jFormattedTextFieldDataMaxEnvio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldDataMaxEnvio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldDataMaxEnvioFocusLost(evt);
            }
        });

        jLabel7.setText("OBS.");

        jTextFieldObs.setToolTipText("");
        jTextFieldObs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldObsKeyPressed(evt);
            }
        });

        jLabel8.setText("Devolução");

        jLabel9.setText("Status Produção");

        jLabel10.setText("Data Produção");

        try {
            jFormattedTextFieldDataProducao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldDataProducao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldDataProducaoFocusLost(evt);
            }
        });

        jComboBoxStatusProducao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pendente", "Pronto", "Enviado", "Estoque", " " }));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortus/icones/save2.png"))); // NOI18N
        jButton2.setText("Salvar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortus/icones/trashcan_delete_17.png"))); // NOI18N
        jButton3.setText("Remover");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortus/icones/folder_new.png"))); // NOI18N
        jButton4.setText("Novo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortus/icones/close.png"))); // NOI18N
        jButton5.setText("Fechar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jComboBoxDevolucao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aguardando", "Ok" }));

        jComboBoxEquipamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ortusonic", "Bioscaler CB", "Bioscaler SB", "Sonic Flex I", "Sonic Flex II", "Biojato", "Led Lux", "Detonix", "Peça(s)" }));

        jTextFieldID.setEditable(false);

        jLabel11.setText("ID");

        jLabelQtdeCarac.setText("Limite 300 letras");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextFieldCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldObs)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jComboBoxDevolucao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addComponent(jComboBoxEquipamento, 0, 92, Short.MAX_VALUE)))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9)
                    .addComponent(jLabel5)
                    .addComponent(jFormattedTextFieldDataPedido)
                    .addComponent(jComboBoxStatusProducao, 0, 92, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jFormattedTextFieldDataMaxEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jFormattedTextFieldDataProducao, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabelQtdeCarac)
                .addGap(314, 314, 314)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldDataPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldDataMaxEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldObs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldDataProducao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxStatusProducao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelQtdeCarac)
                        .addContainerGap(31, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton4)
                            .addComponent(jButton5))
                        .addContainerGap())))
        );

        jTablePendentes.setBackground(new java.awt.Color(255, 255, 204));
        jTablePendentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTablePendentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePendentesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePendentes);

        jButtonAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortus/icones/alterar.png"))); // NOI18N
        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jTextFieldResultado.setEditable(false);

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel12.setText("resultado(s).");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1137, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jTextFieldResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAlterar)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAlterar)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pendente", jPanel4);

        jTableEnviados.setBackground(new java.awt.Color(204, 255, 204));
        jTableEnviados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableEnviados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEnviadosMouseClicked(evt);
            }
        });
        jTableEnviados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableEnviadosKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTableEnviados);

        jTextFieldResultadoEnviadas.setEditable(false);

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel13.setText("resultado(s).");

        jButtonAlterar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortus/icones/alterar.png"))); // NOI18N
        jButtonAlterar1.setText("Alterar");
        jButtonAlterar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1137, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jTextFieldResultadoEnviadas, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAlterar1)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonAlterar1)
                        .addComponent(jLabel13))
                    .addComponent(jTextFieldResultadoEnviadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Enviado", jPanel5);

        jTableEnviadosEstoqueAstec.setBackground(new java.awt.Color(204, 255, 204));
        jTableEnviadosEstoqueAstec.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTableEnviadosEstoqueAstec);

        jTextFieldResultadoEstoqueAsstec.setEditable(false);

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel14.setText("resultado(s).");

        jButtonAlterar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortus/icones/alterar.png"))); // NOI18N
        jButtonAlterar2.setText("Alterar");
        jButtonAlterar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1137, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jTextFieldResultadoEstoqueAsstec, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAlterar2)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldResultadoEstoqueAsstec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14))
                    .addComponent(jButtonAlterar2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Estoque Assistência", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        salvar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        remover();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        novo();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        // TODO add your handling code here:
        alterar();
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonAlterar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterar1ActionPerformed
        // TODO add your handling code here:
        alterarEnviadas();
    }//GEN-LAST:event_jButtonAlterar1ActionPerformed

    private void jButtonAlterar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterar2ActionPerformed
        // TODO add your handling code here:
        alterarEstoqueAstec();
    }//GEN-LAST:event_jButtonAlterar2ActionPerformed

    private void jTextFieldObsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldObsKeyPressed


//        jLabelQtdeCarac.setText(qtdeCarac + qtdeCarcJaDigitado + " digitados");
//        qtdeCarac++;

        jLabelQtdeCarac.setText(String.valueOf(jTextFieldObs.getText().length() + 1));
        //qtdeCarac++;


    }//GEN-LAST:event_jTextFieldObsKeyPressed

    private void jTablePendentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePendentesMouseClicked
        // TODO add your handling code here:
        preencherCamposComDadosDaLinhaPendentes();
    }//GEN-LAST:event_jTablePendentesMouseClicked

    private void jTableEnviadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEnviadosMouseClicked
        // TODO add your handling code here:
        preencherCamposComDadosDaLinhaEnviados();
    }//GEN-LAST:event_jTableEnviadosMouseClicked

    private void jTableEnviadosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableEnviadosKeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode() == 38) {
            try {
                int linha = jTableEnviados.getSelectedRow() - 1;
                preencherCamposComDadosDaLinhaEnviados(linha);
            } catch (Exception e) {
                System.out.println(e);
            }
        } else if (evt.getKeyCode() == 40) {
            try {
                int linha = jTableEnviados.getSelectedRow() + 1;
                preencherCamposComDadosDaLinhaEnviados(linha);
            } catch (Exception e) {
                System.out.println(e);
            }
        }

        //}
        //int linha = jTableEnviados.getSelectedRow()+1;
        //preencherCamposComDadosDaLinhaEnviados(linha);
    }//GEN-LAST:event_jTableEnviadosKeyPressed

    private void jFormattedTextFieldDataPedidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldDataPedidoFocusLost
        // TODO add your handling code here:
        String dataOrigem = jFormattedTextFieldDataPedido.getText();
        String dataCerto = pegarDataAtual(dataOrigem);
        jFormattedTextFieldDataPedido.setText(dataCerto);
    }//GEN-LAST:event_jFormattedTextFieldDataPedidoFocusLost

    private void jFormattedTextFieldDataMaxEnvioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldDataMaxEnvioFocusLost
        // TODO add your handling code here:
        String dataOrigem = jFormattedTextFieldDataMaxEnvio.getText();
        String dataCerto = pegarDataAtual(dataOrigem);
        jFormattedTextFieldDataMaxEnvio.setText(dataCerto);
    }//GEN-LAST:event_jFormattedTextFieldDataMaxEnvioFocusLost

    private void jFormattedTextFieldDataProducaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldDataProducaoFocusLost
        // TODO add your handling code here:
        String dataOrigem = jFormattedTextFieldDataProducao.getText();
        String dataCerto = pegarDataAtual(dataOrigem);
        jFormattedTextFieldDataProducao.setText(dataCerto);
    }//GEN-LAST:event_jFormattedTextFieldDataProducaoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogTabelaTroca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogTabelaTroca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogTabelaTroca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogTabelaTroca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogTabelaTroca dialog = new JDialogTabelaTroca(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonAlterar1;
    private javax.swing.JButton jButtonAlterar2;
    private javax.swing.JComboBox jComboBoxDevolucao;
    private javax.swing.JComboBox jComboBoxEquipamento;
    private javax.swing.JComboBox jComboBoxStatusProducao;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataMaxEnvio;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataPedido;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataProducao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelQtdeCarac;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableEnviados;
    private javax.swing.JTable jTableEnviadosEstoqueAstec;
    private javax.swing.JTable jTablePendentes;
    private javax.swing.JTextField jTextFieldCliente;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldObs;
    private javax.swing.JTextField jTextFieldQtd;
    private javax.swing.JTextField jTextFieldResultado;
    private javax.swing.JTextField jTextFieldResultadoEnviadas;
    private javax.swing.JTextField jTextFieldResultadoEstoqueAsstec;
    // End of variables declaration//GEN-END:variables

    private void povoarTabelaPendente() {
        TabelaTrocaDao cDao = new TabelaTrocaDao();
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{"Cliente", "QTD", "Equipamento", "Data Pedido", "Data Max. Envio", "Obs", "Devolução", "Status Prod.", "Data Prod."});
        trocasPendentes = cDao.obterTrocas("Pendente");

        if (trocasPendentes != null) {
            for (TabelaTroca troca : trocasPendentes) {
                model.addRow(new Object[]{troca.getCliente(), troca.getQtd(), troca.getEquipamento(), troca.getDataPedido(), troca.getDataMaxEnvio(), troca.getObs(), troca.getDevolucao(), troca.getStatusProducao(), troca.getDataProducao()});
            }
            jTablePendentes.setModel(model);
            definirTamanhoDasColunas(jTablePendentes);
        }
        jTextFieldResultado.setText(String.valueOf(trocasPendentes.size()));
    }

    private void povoarTabelaEnviado() {
        TabelaTrocaDao cDao = new TabelaTrocaDao();
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{"Cliente", "QTD", "Equipamento", "Data Pedido", "Data Max. Envio", "Obs", "Devolução", "Status Prod.", "Data Prod."});
        trocasEnviadas = cDao.obterTrocas("Enviado");

        Collections.reverse(trocasEnviadas);
        if (trocasEnviadas != null) {
            for (TabelaTroca troca : trocasEnviadas) {
                model.addRow(new Object[]{troca.getCliente(), troca.getQtd(), troca.getEquipamento(), troca.getDataPedido(), troca.getDataMaxEnvio(), troca.getObs(), troca.getDevolucao(), troca.getStatusProducao(), troca.getDataProducao()});
            }
            jTableEnviados.setModel(model);
            definirTamanhoDasColunas(jTableEnviados);
        }
        //Collections.reverse(trocasEnviadas);
        jTextFieldResultadoEnviadas.setText(String.valueOf(trocasEnviadas.size()));
    }

    private void salvar() {
        if (!validarCampos()) {
            return;
        }
        int opcao = JOptionPane.showConfirmDialog(rootPane,
                "Deseja salvar?", "Confirmação",
                JOptionPane.YES_NO_OPTION);
        if (opcao != JOptionPane.YES_OPTION) {
            return;
        }
        TabelaTroca troca = new TabelaTroca();
        if (!jTextFieldID.getText().isEmpty()) {
            troca.setId(Integer.parseInt(jTextFieldID.getText()));
        }
        troca.setCliente(jTextFieldCliente.getText());
        troca.setQtd(jTextFieldQtd.getText());
        troca.setEquipamento(jComboBoxEquipamento.getSelectedItem().toString());
        troca.setDataPedido(jFormattedTextFieldDataPedido.getText());
        troca.setDataMaxEnvio(jFormattedTextFieldDataMaxEnvio.getText());
        troca.setObs(jTextFieldObs.getText());
        troca.setDevolucao(jComboBoxDevolucao.getSelectedItem().toString());
        troca.setStatusProducao(jComboBoxStatusProducao.getSelectedItem().toString());
        troca.setDataProducao(jFormattedTextFieldDataProducao.getText());

        Usuario user = (Usuario) HashSistema.hash.get("usuarioLogado");
        String ip = pegarIPDaMaquina();
        Log log = new Log(user, Utilidades.retData(), "Desktop", "Inserto/Update", ip);
        
        if (troca.getMomentoAuteracao() == null) {
            List<Log> logs = new ArrayList<Log>();
            logs.add(log);
            troca.setMomentoAuteracao(logs);
        } else {
            troca.getMomentoAuteracao().add(log);
            troca.setMomentoAuteracao(troca.getMomentoAuteracao());
        }


        TransactionManager.beginTransaction();
        try {
            TabelaTrocaDao tDao = new TabelaTrocaDao();
            new LogDao().persistir(log);
            tDao.persistir(troca);

            TransactionManager.commit();

            JOptionPane.showMessageDialog(null, "Troca foi gravada!");
            povoarTabelaPendente();
            povoarTabelaEnviado();
            novo();
        } catch (Exception e) {
            TransactionManager.rollback();
            JOptionPane.showMessageDialog(null, "Cliente não pode ser gravado!" + e);
        }
    }

    private boolean validarCampos() {
        if (jTextFieldID.getText().isEmpty() && jTextFieldCliente.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O cliente deve ser preenchido!");
            return false;
        }
        return true;
    }

    private void novo() {
        jTextFieldID.setText(null);
        jTextFieldCliente.setText(null);
        jTextFieldQtd.setText(null);
        jComboBoxEquipamento.setSelectedIndex(0);
        jFormattedTextFieldDataPedido.setText(null);
        jFormattedTextFieldDataMaxEnvio.setText(null);
        jTextFieldObs.setText(null);
        jComboBoxDevolucao.setSelectedIndex(0);
        jComboBoxStatusProducao.setSelectedIndex(0);
        jFormattedTextFieldDataProducao.setText(null);
    }

    private void remover() {
        int opcao = JOptionPane.showConfirmDialog(rootPane,
                "Deseja mesmo remover?", "Confirmação",
                JOptionPane.YES_NO_OPTION);
        if (opcao != JOptionPane.YES_OPTION) {
            return;
        }
        if (!jTextFieldID.getText().isEmpty()) {
            TransactionManager.beginTransaction();
            try {
                TabelaTrocaDao tDao = new TabelaTrocaDao();
                TabelaTroca troca = tDao.obterPorId(Integer.parseInt(jTextFieldID.getText()));
                tDao.remover(troca);
                TransactionManager.commit();
                povoarTabelaEnviado();
                povoarTabelaPendente();
                novo();
                JOptionPane.showMessageDialog(null, "Troca removida com sucesso!");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro! Não foi possivel excluir a troca!\n" + e);
                return;
            }
        } else {
            JOptionPane.showMessageDialog(null, "ID inválido! Selecione uma troca válido para excluir!");
            return;
        }
    }

    private void alterar() {
        int linha = jTablePendentes.getSelectedRow();
        if (linha != -1) {
            TabelaTroca troca = trocasPendentes.get(linha);
            preencherFormularioComDados(troca);
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha para editar a troca.");
            return;
        }
    }

    private void preencherFormularioComDados(TabelaTroca troca) {
        jTextFieldID.setText(String.valueOf(troca.getId()));
        jTextFieldCliente.setText(troca.getCliente());
        jTextFieldQtd.setText(troca.getQtd());
        jComboBoxEquipamento.setSelectedIndex(definirQualEquipamento(troca.getEquipamento()));
        jFormattedTextFieldDataPedido.setText(troca.getDataPedido());
        jFormattedTextFieldDataMaxEnvio.setText(troca.getDataMaxEnvio());
        jFormattedTextFieldDataProducao.setText(troca.getDataProducao());
        jTextFieldObs.setText(troca.getObs());
        jComboBoxDevolucao.setSelectedIndex(definirQualDevolucao(troca.getDevolucao()));
        jComboBoxStatusProducao.setSelectedIndex(definirQualStatusProducao(troca.getStatusProducao()));
        jFormattedTextFieldDataProducao.setText(troca.getDataProducao());
        jLabelQtdeCarac.setText(String.valueOf(jTextFieldObs.getText().length()));
        jLabelQtdeCarac.setText(String.valueOf(jTextFieldObs.getText().length() + 1));
    }

    private int definirQualEquipamento(String descricao) {
        int cont = 0;
        while (cont < jComboBoxEquipamento.getItemCount()) {
            if (descricao.equals(jComboBoxEquipamento.getItemAt(cont).toString())) {
                return cont;
            }
            cont++;
        }
        return cont;
    }

    private int definirQualDevolucao(String descricao) {
        int cont = 0;
        while (cont < jComboBoxDevolucao.getItemCount()) {
            if (descricao.equals(jComboBoxDevolucao.getItemAt(cont).toString())) {
                return cont;
            }
            cont++;
        }
        return cont;
    }

    private int definirQualStatusProducao(String statusProducao) {
        int cont = 0;
        while (cont < jComboBoxStatusProducao.getItemCount()) {
            if (statusProducao.equals(jComboBoxStatusProducao.getItemAt(cont).toString())) {
                return cont;
            }
            cont++;
        }
        return cont;
    }

    private void alterarEnviadas() {
        int linha = jTableEnviados.getSelectedRow();
        if (linha != -1) {
            TabelaTroca troca = trocasEnviadas.get(linha);
            preencherFormularioComDados(troca);
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha para editar a troca.");
            return;
        }
    }

    private void povoarTabelaEstoque() {
        TabelaTrocaDao cDao = new TabelaTrocaDao();
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{"Cliente", "QTD", "Equipamento", "Data Pedido", "Data Max. Envio", "Obs", "Devolução", "Status Prod.", "Data Prod."});
        trocasEstoque = cDao.obterTrocas("Estoque");

        if (trocasEstoque != null) {
            for (TabelaTroca troca : trocasEstoque) {
                model.addRow(new Object[]{troca.getCliente(), troca.getQtd(), troca.getEquipamento(), troca.getDataPedido(), troca.getDataMaxEnvio(), troca.getObs(), troca.getDevolucao(), troca.getStatusProducao(), troca.getDataProducao()});
            }
            jTableEnviadosEstoqueAstec.setModel(model);
            definirTamanhoDasColunas(jTableEnviadosEstoqueAstec);
        }
        jTextFieldResultadoEstoqueAsstec.setText(String.valueOf(trocasEstoque.size()));
    }

    private void alterarEstoqueAstec() {
        int linha = jTableEnviadosEstoqueAstec.getSelectedRow();
        if (linha != -1) {
            TabelaTroca troca = trocasEstoque.get(linha);
            preencherFormularioComDados(troca);
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha para editar a troca.");
            return;
        }
    }

    private void definirTamanhoDasColunas(JTable tabela) {
        tabela.getColumnModel().getColumn(0).setPreferredWidth(280);
        tabela.getColumnModel().getColumn(1).setPreferredWidth(40);
    }

    private void preencherCamposComDadosDaLinhaPendentes() {
        int linha = jTablePendentes.getSelectedRow();
        if (linha != -1) {
            TabelaTroca troca = trocasPendentes.get(linha);
            preencherFormularioComDados(troca);
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha para editar a troca.");
            return;
        }
    }

    private void preencherCamposComDadosDaLinhaEnviados() {
        int linha = jTableEnviados.getSelectedRow();
        if (linha != -1) {
            //Collections.reverse(trocasEnviadas);
            TabelaTroca troca = trocasEnviadas.get(linha);
            preencherFormularioComDados(troca);
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha para editar a troca.");
            return;
        }
    }

    private void preencherCamposComDadosDaLinhaEnviados(int linha) {
        if (linha != -1 || linha > trocasEnviadas.size()) {
            //Collections.reverse(trocasEnviadas);
            TabelaTroca troca = trocasEnviadas.get(linha);
            preencherFormularioComDados(troca);
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha para editar a troca.");
            return;
        }
    }

    private String pegarDataAtual(String dataOrigem) {
        if (dataOrigem.equals("  /  /    ")) {
            String data = "";
            data = new Utilidades().calendarToString(Calendar.getInstance());
            return data;
        } else {
            return dataOrigem;
        }
    }

    private String pegarIPDaMaquina() {
        try {
            return InetAddress.getLocalHost().getHostAddress() + " - " + InetAddress.getLocalHost().getHostName();
        } catch (Exception e) {
            System.out.println(e);
            return " . . . ";
        }
    }
}
