/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFrameAstec.java
 *
 * Created on 21/12/2011, 17:44:02
 */
package br.com.ortus.gui;

import br.com.ortus.beans.ControleAcesso;
import br.com.ortus.beans.Log;
import br.com.ortus.beans.Usuario;
import br.com.ortus.configuracaoPersistencia.TransactionManager;
import br.com.ortus.daosSistema.ControleAcessoDao;
import br.com.ortus.daosSistema.LogDao;
import br.com.ortus.utilidades.HashSistema;
import br.com.ortus.utilidades.Utilidades;
import java.net.InetAddress;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Paulo Azevedo email: paulovulture@hotmail.com 12/2011 - 01/2012
 */
public class JFrameAstec extends javax.swing.JFrame {

    /**
     * Creates new form JFrameAstec
     */
    public JFrameAstec() {
        initComponents();
        mensagemDeBoasVindas();
        ativarControleDeAcesso();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jMenuPrincipal1 = new javax.swing.JButton();
        jMenuPrincipal2 = new javax.swing.JButton();
        jMenuPrincipal3 = new javax.swing.JButton();
        jMenuPrincipal4 = new javax.swing.JButton();
        jMenuPrincipal5 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButtonSobre = new javax.swing.JButton();
        jMenuPrincipal6 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuPrincipal7 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelBemVindo = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuSuperioCad1 = new javax.swing.JMenuItem();
        jMenuSuperioCad2 = new javax.swing.JMenuItem();
        jMenuSuperioCad3 = new javax.swing.JMenuItem();
        jMenuSuperioCad4 = new javax.swing.JMenuItem();
        jMenuSuperioCad5 = new javax.swing.JMenuItem();
        jMenuSuperioCad6 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuSistema = new javax.swing.JMenuItem();
        jMenuLog = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Assistencia Técnica Ortus - Tela Principal");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jToolBar1.setRollover(true);

        jMenuPrincipal1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortus/icones/usercard_01.png"))); // NOI18N
        jMenuPrincipal1.setToolTipText("Cadastro de Usuário");
        jMenuPrincipal1.setFocusable(false);
        jMenuPrincipal1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuPrincipal1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jMenuPrincipal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPrincipal1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jMenuPrincipal1);

        jMenuPrincipal2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortus/icones/users.png"))); // NOI18N
        jMenuPrincipal2.setToolTipText("Cadastro de Cliente");
        jMenuPrincipal2.setFocusable(false);
        jMenuPrincipal2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuPrincipal2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jMenuPrincipal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPrincipal2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jMenuPrincipal2);

        jMenuPrincipal3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortus/icones/gnome_dev_media_cf.png"))); // NOI18N
        jMenuPrincipal3.setToolTipText("Cadastro de Componente");
        jMenuPrincipal3.setFocusable(false);
        jMenuPrincipal3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuPrincipal3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jMenuPrincipal3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPrincipal3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jMenuPrincipal3);

        jMenuPrincipal4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortus/icones/hwbrowser.png"))); // NOI18N
        jMenuPrincipal4.setToolTipText("Cadastro de Equipamento");
        jMenuPrincipal4.setFocusable(false);
        jMenuPrincipal4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuPrincipal4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jMenuPrincipal4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPrincipal4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jMenuPrincipal4);

        jMenuPrincipal5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortus/icones/settings.png"))); // NOI18N
        jMenuPrincipal5.setToolTipText("Cadastro de Assistência");
        jMenuPrincipal5.setFocusable(false);
        jMenuPrincipal5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuPrincipal5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jMenuPrincipal5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPrincipal5ActionPerformed(evt);
            }
        });
        jToolBar1.add(jMenuPrincipal5);
        jToolBar1.add(jSeparator1);

        jButtonSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortus/icones/info.png"))); // NOI18N
        jButtonSobre.setFocusable(false);
        jButtonSobre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSobre.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSobreActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonSobre);

        jMenuPrincipal6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortus/icones/exchange.png"))); // NOI18N
        jMenuPrincipal6.setToolTipText("Cadastro de Trocas");
        jMenuPrincipal6.setFocusable(false);
        jMenuPrincipal6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuPrincipal6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jMenuPrincipal6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPrincipal6ActionPerformed(evt);
            }
        });
        jToolBar1.add(jMenuPrincipal6);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortus/icones/cash.png"))); // NOI18N
        jButton2.setText("Peças");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jMenuPrincipal7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortus/icones/emblem_money.png"))); // NOI18N
        jMenuPrincipal7.setToolTipText("Cadastro de Pedidos");
        jMenuPrincipal7.setFocusable(false);
        jMenuPrincipal7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuPrincipal7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jMenuPrincipal7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPrincipal7ActionPerformed(evt);
            }
        });
        jToolBar1.add(jMenuPrincipal7);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortus/icones/close2.png"))); // NOI18N
        jButton1.setMnemonic('f');
        jButton1.setToolTipText("Sair do sistema");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortus/icones/LOGO NOVA.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(228, 228, 228))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        jLabelBemVindo.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabelBemVindo.setForeground(new java.awt.Color(0, 51, 153));
        jLabelBemVindo.setText("Boas Vindas");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortus/icones/manual.png"))); // NOI18N
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jMenu1.setMnemonic('C');
        jMenu1.setText("Cadastros");

        jMenuSuperioCad1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMenuSuperioCad1.setText("Usuario");
        jMenuSuperioCad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSuperioCad1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuSuperioCad1);

        jMenuSuperioCad2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuSuperioCad2.setText("Cliente");
        jMenuSuperioCad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSuperioCad2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuSuperioCad2);

        jMenuSuperioCad3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuSuperioCad3.setText("Componente");
        jMenuSuperioCad3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSuperioCad3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuSuperioCad3);

        jMenuSuperioCad4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuSuperioCad4.setText("Equipamento");
        jMenuSuperioCad4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSuperioCad4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuSuperioCad4);

        jMenuSuperioCad5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuSuperioCad5.setText("Assistência");
        jMenuSuperioCad5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSuperioCad5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuSuperioCad5);

        jMenuSuperioCad6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuSuperioCad6.setText("Estoque Produtos");
        jMenuSuperioCad6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSuperioCad6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuSuperioCad6);

        jMenuBar1.add(jMenu1);

        jMenu3.setMnemonic('s');
        jMenu3.setText("Sistema");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuSistema.setText("Acesso Usuários");
        jMenuSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSistemaActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuSistema);

        jMenuLog.setText("Log de Acesso");
        jMenuLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLogActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuLog);

        jMenuBar1.add(jMenu3);

        jMenu4.setMnemonic('a');
        jMenu4.setText("Ajuda");

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortus/icones/graphic_design.png"))); // NOI18N
        jMenuItem8.setText("Sobre o Sistema");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem8);

        jMenuBar1.add(jMenu4);

        jMenu5.setMnemonic('r');
        jMenu5.setText("Sair");

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortus/icones/logOut.png"))); // NOI18N
        jMenuItem6.setText("Logoff");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem6);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortus/icones/sair.png"))); // NOI18N
        jMenuItem7.setText("Fechar");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem7);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1116, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBemVindo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1116, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelBemVindo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuPrincipal3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPrincipal3ActionPerformed
        // TODO add your handling code here:
        JDialog jd = new JDialogCadastroComponenteCerto(this, true);
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);
    }//GEN-LAST:event_jMenuPrincipal3ActionPerformed

    private void jMenuPrincipal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPrincipal1ActionPerformed
        // TODO add your handling code here:
        JDialog jd = new JDialogCadastroUsuario(this, true);
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);
    }//GEN-LAST:event_jMenuPrincipal1ActionPerformed

    private void jMenuPrincipal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPrincipal2ActionPerformed
        // TODO add your handling code here:
        JDialog jd = new NovoCadastroCliente(this, true);
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);
    }//GEN-LAST:event_jMenuPrincipal2ActionPerformed

    private void jMenuPrincipal4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPrincipal4ActionPerformed
        // TODO add your handling code here:
        JDialog jd = new JDialogNovoCadastroEquipamento(this, true);
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);
    }//GEN-LAST:event_jMenuPrincipal4ActionPerformed

private void jMenuPrincipal5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPrincipal5ActionPerformed
// TODO add your handling code here:
    JDialog jd = new JDialogAssitencia(this, true);
    jd.setLocationRelativeTo(null);
    jd.setVisible(true);
}//GEN-LAST:event_jMenuPrincipal5ActionPerformed

    private void jButtonSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSobreActionPerformed
        // TODO add your handling code here:
        JDialog jd = new JDialogSobre(this, true);
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);
    }//GEN-LAST:event_jButtonSobreActionPerformed

    private void jMenuPrincipal6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPrincipal6ActionPerformed
        // TODO add your handling code here:
        JDialog jd = new JDialogTabelaTroca(this, true);
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);
    }//GEN-LAST:event_jMenuPrincipal6ActionPerformed

    private void jMenuPrincipal7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPrincipal7ActionPerformed
        // TODO add your handling code here:
        JDialog jd = new JDialogPedidosReservados(this, true);
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);
    }//GEN-LAST:event_jMenuPrincipal7ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        fechar();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        logoff();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        JDialog jd = new JDialogSobre(this, true);
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSistemaActionPerformed
        // TODO add your handling code here:
        JDialog jd = new JDialogControleAcessos(this, true);
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);
    }//GEN-LAST:event_jMenuSistemaActionPerformed

    private void jMenuSuperioCad6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSuperioCad6ActionPerformed
        // TODO add your handling code here:
        JDialog jd = new JDialogEstoqueProduto(this, true);
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);
    }//GEN-LAST:event_jMenuSuperioCad6ActionPerformed

    private void jMenuSuperioCad5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSuperioCad5ActionPerformed
// TODO add your handling code here:
        JDialog jd = new JDialogAssitencia(this, true);
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);
    }//GEN-LAST:event_jMenuSuperioCad5ActionPerformed

    private void jMenuSuperioCad4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSuperioCad4ActionPerformed
        // TODO add your handling code here:
        JDialog jd = new JDialogNovoCadastroEquipamento(this, true);
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);
    }//GEN-LAST:event_jMenuSuperioCad4ActionPerformed

    private void jMenuSuperioCad3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSuperioCad3ActionPerformed
        // TODO add your handling code here:
        JDialog jd = new JDialogCadastroComponenteCerto(this, true);
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);
    }//GEN-LAST:event_jMenuSuperioCad3ActionPerformed

    private void jMenuSuperioCad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSuperioCad2ActionPerformed
        // TODO add your handling code here:
        JDialog jd = new NovoCadastroCliente(this, true);
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);
    }//GEN-LAST:event_jMenuSuperioCad2ActionPerformed

    private void jMenuSuperioCad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSuperioCad1ActionPerformed
        // TODO add your handling code here:
        JDialog jd = new JDialogCadastroUsuario(this, true);
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);
    }//GEN-LAST:event_jMenuSuperioCad1ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenuLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLogActionPerformed
        // TODO add your handling code here:
        JDialog jd = new JDialogLog(this, true);
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);
    }//GEN-LAST:event_jMenuLogActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        fechar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JDialog jd = new JDialogListagemPecasEPrecos(this, true);
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        JDialog jd = new JDialogSobre(this, true);
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);
    }//GEN-LAST:event_jButton3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameAstec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameAstec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameAstec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameAstec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameAstec().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonSobre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBemVindo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuLog;
    private javax.swing.JButton jMenuPrincipal1;
    private javax.swing.JButton jMenuPrincipal2;
    private javax.swing.JButton jMenuPrincipal3;
    private javax.swing.JButton jMenuPrincipal4;
    private javax.swing.JButton jMenuPrincipal5;
    private javax.swing.JButton jMenuPrincipal6;
    private javax.swing.JButton jMenuPrincipal7;
    private javax.swing.JMenuItem jMenuSistema;
    private javax.swing.JMenuItem jMenuSuperioCad1;
    private javax.swing.JMenuItem jMenuSuperioCad2;
    private javax.swing.JMenuItem jMenuSuperioCad3;
    private javax.swing.JMenuItem jMenuSuperioCad4;
    private javax.swing.JMenuItem jMenuSuperioCad5;
    private javax.swing.JMenuItem jMenuSuperioCad6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

    private void fechar() {
        int opcao = JOptionPane.showConfirmDialog(rootPane,
                "Deseja mesmo fechar o programa?", "Confirmação",
                JOptionPane.YES_NO_OPTION);
        if (opcao != JOptionPane.YES_OPTION) {
            return;
        } else {
            Usuario user = (Usuario) HashSistema.hash.get("usuarioLogado");
            try {
                TransactionManager.beginTransaction();
                String ip = pegarIPDaMaquina();
                new LogDao().persistir(new Log(user, Utilidades.retData(), "Desktop", "Saida", ip));
                TransactionManager.commit();
            } catch (Exception e) {
                System.out.println(e);
            } finally {
                HashSistema.hash.remove("usuarioLogado");
                System.exit(0);
            }
        }
    }

    private void logoff() {
        int opcao = JOptionPane.showConfirmDialog(rootPane,
                "Deseja mesmo sair?", "Confirmação",
                JOptionPane.YES_NO_OPTION);
        if (opcao != JOptionPane.YES_OPTION) {
            return;
        }
        Usuario user = (Usuario) HashSistema.hash.get("usuarioLogado");
        try {
            TransactionManager.beginTransaction();
            String ip = pegarIPDaMaquina();
            new LogDao().persistir(new Log(user, Utilidades.retData(), "Desktop", "Saida", ip));
            TransactionManager.commit();
        } catch (Exception e) {
            System.out.println(e);
        } finally {
            HashSistema.hash.remove("usuarioLogado");
            dispose();
            JDialog jd = new JDialogLogin(this, true);
            jd.setLocationRelativeTo(null);
            jd.setVisible(true);
        }
    }

    private void mensagemDeBoasVindas() {
        Usuario user = (Usuario) HashSistema.hash.get("usuarioLogado");
        //System.out.println(Calendar.getInstance());
        jLabelBemVindo.setText("Seja bem vindo " + user.getNome() + ", você entrou no sistema em: " + new Utilidades().dateParaDataEHora(new Date()));
    }

    private void ativarControleDeAcesso() {
        ControleAcessoDao cDao = new ControleAcessoDao();
        Usuario user = (Usuario) HashSistema.hash.get("usuarioLogado");
        if (!user.getNome().equals("admin")) {
            ControleAcesso controle = cDao.obterLista(" usuario_id='" + user.getId() + "'").get(0);
            if (controle != null) {
                habilitarMenuSuperior(controle);
                habilitarMenuPrincipal(controle);
                jMenuSistema.setEnabled(false);
                jMenuLog.setEnabled(false);
            }
        }
    }

    private void habilitarMenuSuperior(ControleAcesso controle) {
        String[] menuSuperior = controle.getAcessoMenuSuperio();
        if (menuSuperior[0].equals("1")) {
            jMenuSuperioCad1.setEnabled(true);
        } else {
            jMenuSuperioCad1.setEnabled(false);
        }
        if (menuSuperior[1].equals("1")) {
            jMenuSuperioCad2.setEnabled(true);
        } else {
            jMenuSuperioCad2.setEnabled(false);
        }
        if (menuSuperior[2].equals("1")) {
            jMenuSuperioCad3.setEnabled(true);
        } else {
            jMenuSuperioCad3.setEnabled(false);
        }
        if (menuSuperior[3].equals("1")) {
            jMenuSuperioCad4.setEnabled(true);
        } else {
            jMenuSuperioCad4.setEnabled(false);
        }
        if (menuSuperior[4].equals("1")) {
            jMenuSuperioCad5.setEnabled(true);
        } else {
            jMenuSuperioCad5.setEnabled(false);
        }
        if (menuSuperior[5].equals("1")) {
            jMenuSuperioCad6.setEnabled(true);
        } else {
            jMenuSuperioCad6.setEnabled(false);
        }
    }

    private void habilitarMenuPrincipal(ControleAcesso controle) {
        String[] menuPrincipal = controle.getAcessoMenuPrincipal();
        if (menuPrincipal[0].equals("1")) {
            jMenuPrincipal1.setEnabled(true);
        } else {
            jMenuPrincipal1.setEnabled(false);
        }
        if (menuPrincipal[1].equals("1")) {
            jMenuPrincipal2.setEnabled(true);
        } else {
            jMenuPrincipal2.setEnabled(false);
        }
        if (menuPrincipal[2].equals("1")) {
            jMenuPrincipal3.setEnabled(true);
        } else {
            jMenuPrincipal3.setEnabled(false);
        }
        if (menuPrincipal[3].equals("1")) {
            jMenuPrincipal4.setEnabled(true);
        } else {
            jMenuPrincipal4.setEnabled(false);
        }
        if (menuPrincipal[4].equals("1")) {
            jMenuPrincipal5.setEnabled(true);
        } else {
            jMenuPrincipal5.setEnabled(false);
        }
        if (menuPrincipal[5].equals("1")) {
            jMenuPrincipal6.setEnabled(true);
        } else {
            jMenuPrincipal6.setEnabled(false);
        }
        if (menuPrincipal[6].equals("1")) {
            jMenuPrincipal7.setEnabled(true);
        } else {
            jMenuPrincipal7.setEnabled(false);
        }
    }

    private String pegarIPDaMaquina() {
        try {
            return InetAddress.getLocalHost().getHostAddress() + " - " +InetAddress.getLocalHost().getHostName();
        } catch (Exception e) {
            System.out.println(e);
            return " . . . ";
        }

    }
}
